let otrosProductos = [
  {
    id: 10,
    nombre: "Muffin de Arándanos",
    precio: 2.5,
    categoria: "Repostería",
    imagen: "../imagenes/muffin_arandanos.jpg",
  },
  {
    id: 11,
    nombre: "Té Verde",
    precio: 2.0,
    categoria: "Bebidas",
    imagen: "../imagenes/te_verde.jpg",
  },
  {
    id: 12,
    nombre: "Té Negro",
    precio: 2.0,
    categoria: "Bebidas",
    imagen: "../imagenes/te_negro.jpg",
  },
  {
    id: 13,
    nombre: "Café Mocha",
    precio: 3.8,
    categoria: "Bebidas",
    imagen: "../imagenes/mocha.jpg",
  },
  {
    id: 14,
    nombre: "Café con Leche",
    precio: 3.0,
    categoria: "Bebidas",
    imagen: "../imagenes/cafe_leche.jpg",
  },
  {
    id: 15,
    nombre: "Pan de Banana",
    precio: 2.5,
    categoria: "Panadería",
    imagen: "../imagenes/pan_banana.jpg",
  },
  {
    id: 16,
    nombre: "Donut Glaseado",
    precio: 1.8,
    categoria: "Panadería",
    imagen: "../imagenes/donut.jpg",
  },
  {
    id: 17,
    nombre: "Cheesecake",
    precio: 3.5,
    categoria: "Repostería",
    imagen: "../imagenes/cheesecake.jpg",
  },
  {
    id: 18,
    nombre: "Macaron",
    precio: 1.5,
    categoria: "Repostería",
    imagen: "../imagenes/macaron.jpg",
  },
];
